### ISSUE TITLE
problem in running the software

### ISSUE THREAD

**Issue by ghost** [mohammed97ashraf/Fake_news_Detection#1]
i am trying to run the program but its giving me errors 
![image](https://github.com/user-attachments/assets/ca0563fe-fad3-421e-b46f-2378fcb9500e)

**Comment by mohammed97ashraf** [comment]
## Update the model path in joblib
```Model = joblib.load('C:/Users/Ashraf/Desktop/Fake_news_Detection/Model.pkl')  # Update the path according to your folder/directory```

Alternatively, you can replace the model loading code with the following:

```python
import os

parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
model_path = os.path.join(parent_dir, "Model.pkl")
print(f"Corrected model path: {model_path}")

Model = joblib.load(model_path)
```
## You may also pull the latest changes from the repository, as I have fixed this issue there.
